### ISSUE TITLE
Backups are not working with postgres 12

### ISSUE THREAD

**Issue by paulmiu** [minhng92/odoo-13-docker-compose#1]
If I'm trying to backup my database with the database manager (<URL>/web/database/manager), I'm getting an error like this:

```
Database backup error: Postgres subprocess ('/usr/bin/pg_dump', '--no-owner', '--file=/tmp/tmprbbw04qj/dump.sql', '<DB_NAME>') error 1
```

After changing the postgres version in the docker compose file from `12` to `11` it's working again.

https://github.com/minhng92/odoo-13-docker-compose/blob/86f4a9408859b09d8e587de43ddf0e32586d57b9/docker-compose.yml#L4

**Comment by minhng92** [comment]
Thank you @mamiu 
I don't have enough spare time to fix it using postgres 12. Just downgrade to version 11.
Resolved at this commit based on your suggestion: 1b4516b

**Comment by nekopep** [comment]
A quick update, adding this to your dockerfile will update postgresql cient to latest version and will solve the issue with postgresql12. (Avoid to downgrade :D)

#upgrade posgresql client
# install latest postgresql-client
RUN echo 'deb http://apt.postgresql.org/pub/repos/apt/ buster-pgdg main' > /etc/apt/sources.list.d/pgdg.list \
        && GNUPGHOME="$(mktemp -d)" \
        && export GNUPGHOME \
        && repokey='B97B0AFCAA1A47F044F244A07FCC7D46ACCC4CF8' \
        && gpg --batch --keyserver keyserver.ubuntu.com --recv-keys "${repokey}" \
        && gpg --batch --armor --export "${repokey}" > /etc/apt/trusted.gpg.d/pgdg.gpg.asc \
        && gpgconf --kill all \
        && rm -rf "$GNUPGHOME" \
        && apt-get update  \
        && apt-get install --no-install-recommends -y postgresql-client \
        && rm -f /etc/apt/sources.list.d/pgdg.list \
        && rm -rf /var/lib/apt/lists/*

Comes from here:
https://github.com/llacroix/odoo-docker/commit/2f8364658daf2f99d7dd8a3dfbb9af9303e431b5

**Comment by mandayugana** [comment]
I experienced the same error with dockerized Odoo 11 with PostgreSQL 10. The `pg_dump` version in Odoo 11 container is 9.5. It seems that `pg_dump` 9.5 can't read PostgreSQL 10 database. I fixed it by replacing `postgresql-client` version 9.5 with version 10.

I added these lines into Dockerfile.
```
RUN apt remove postgresql-client* -y
RUN apt install wget
RUN echo 'deb http://apt.postgresql.org/pub/repos/apt/ xenial-pgdg main' >> /etc/apt/sources.list.d/pgdg.list
RUN wget --no-check-certificate --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -

RUN apt update
RUN apt install postgresql-client-10
```

The point is `postgresql-client` must be able to read the database in PostgreSQL server.
