### ISSUE TITLE
Database not persistent

### ISSUE THREAD

**Issue by plain-solutions-gmbh** [minhng92/odoo-13-docker-compose#2]
Please adding do composer-file:
```
volumes:
        - ./postgresql:/var/lib/postgresql/data
```
add Postgres-Rawdata to that folder.

Thx

**Comment by minhng92** [comment]
Thank you @youngcut 
Resolved at this commit based on your suggestion: https://github.com/minhng92/odoo-13-docker-compose/commit/1b4516bb5f3e13af47b910ffea97a84cee6b14c6
